[workspace]
members = [
    "web/dashboard",
    "web/api",
    "web/api/migration",
    "web/website",
]
resolver = "2"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
